$(function(){
  $(".headerx").load("../../assets/header.html"); 
});
$(function(){
  $(".footerx").load("../../assets/footer.html"); 
});
$(function(){
  $(".mobileNav").load("../../assets/mobileNav.html"); 
});
$(function(){
  $(".settingsMenuBg").load("../../assets/settings.html"); 
});
